spring-boot-category
RandomEastEcho/SpringBootIntro pull request #9
Opened 2023-10-30 11:07 UTC by RandomEastEcho

Added category model

2023-10-31 11:00 UTC, yevheniisynytsia requested changes
Nice! Let's improve the solution a bit

2023-10-31 11:00 UTC, yevheniisynytsia commented on src/main/java/com/example/springbootintro/controller/CategoryController.java
> +@RequestMapping("api/categories")
```suggestion
@RequestMapping("/api/categories")
```
I guess you missed it

2023-10-31 11:00 UTC, yevheniisynytsia commented on src/main/java/com/example/springbootintro/mapper/BookMapper.java
> +    }
the task also says you have to add a method with `@Named` annotation. 
This can be helpful in your next mappers that can be more complicated. The method should return a new book object, and if id != null, with the id set.

2023-10-31 11:00 UTC, yevheniisynytsia commented on src/main/java/com/example/springbootintro/service/impl/CategoryServiceImpl.java
> +        Category category = categoryRepository.findById(id).get();
orEsleThrow will look good here I think
get can cause exception

2023-11-01 11:38 UTC, RandomEastEcho commented on src/main/java/com/example/springbootintro/mapper/BookMapper.java
> +    }
This is required for next task ShoppingCart not for Category 
![изображение_2023-11-01_133844236](https://github.com/RandomEastEcho/SpringBootIntro/assets/124060117/4c7ef152-4ef3-41fd-bd2b-74967e7e7657)

2023-11-02 11:19 UTC, yevheniisynytsia approved these changes

2023-11-03 10:13 UTC, merged